name: Build and upload to GitHub Pages

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Build
        run: |
          echo "::group::Build"
          npm ci
          npm run build -- --base-href=/${{ github.event.repository.name }}/
          echo "::endgroup::"

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist/${{ github.event.repository.name }}/browser

      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
